### ISSUE TITLE
Mettre en évidence les cours n'ayant pas de professeurs associés

### ISSUE THREAD

**Issue by Ewennnn** [kernoeb/PlanningSup#108]
Depuis le BUT3, c'est une galère d'organisation pour les IUT, surtout pour la 3ème année. A Nantes, on a près de 80% de nos cours qui ne sont pas assurés. Les cours non assurés sont quand même mis sur l'emploi du temps pour qu'on puisse se rendre compte de l'ampleur de problème. Ce serrait cool de mettre ces heures de cours non assurés en évidence sur planningsup en changeant la couleur de fond des créneaux comme ça par exemple :
![image](https://github.com/kernoeb/PlanningSup/assets/71500365/ab30d62e-2ad8-48de-b460-f2dbb3b49ecd)

On sait qu'un cours n'est pas assuré car il n'a pas de profs associé. On peut vérifier la présence d'un prof avec la propriété `Personnel` dans le fichier ICS ou par la présence d'une seconde virgule dans le `SUMMARY` du créneau de cours :
```
SUMMARY:TD - Politique de communication\, Info 3 Groupe Alternance\, TOURNÈS Fabienne
LOCATION:J-C0/02
DESCRIPTION:Matière : Politique de communication\nPersonnel : TOURNÈS Fabienne\nGroupe : Info 3 Groupe Alternance\nSalle : J-C0/02\n
```

On pourrait ajouter une option permettant de mettre en évidence ou non ces heures de cours avec dans les paramètres une case à cocher "**Mettre en évidence les événements qui n'ont pas de professeur associé**"

Le but n'est pas de cacher ces heures de cours, mais simplement de les mettre en évidences. On ne sera surement pas la seule promo à avoir ce soucis et il ne faudrait pas cacher le problème mais le laisser visible pour que les choses changent.

**Comment by kernoeb** [comment]
Merged in [2.14.0](https://github.com/kernoeb/PlanningSup/commit/796a0c25eb2977276d585ce8c8d5e1baf2cb6924) ✨
