### ISSUE TITLE
[SUGGESTION] Amélioration du README

### ISSUE THREAD

**Issue by sikelio** [kernoeb/PlanningSup#112]
Le projet est super sympa, mais j'ai un poil galéré à comprendre comment lancer en mode dev. J'ai du passer bien 2h avant d'avoir tout setup pour faire des tests en local.

Je peux m'en charger s'il faut dès que j'ai le temps.

PS: Je viens de mettre le nez dans docker depuis seulement quelques semaines ça peux expliquer pourquoi j'ai autant galéré mais si on part de l'dée qu'un débutant comme moi (actuellement) tombe sur ce projet il sera peut être pas en mesure de le tester en local

**Comment by kernoeb** [comment]
Hello ! 
Qu'est-ce qu'il manque ici ? 

https://github.com/kernoeb/PlanningSup#d%C3%A9veloppement

La seule chose que je vois qui pourrait manquer c'est de mettre localhost:27017 dans le `.env` dans ce cas, mais autrement c'est techniquement suffisant ?

**Comment by kernoeb** [comment]
En fait `pnpm run dev` est suffisant même, je vais corriger ça déjà

**Comment by kernoeb** [comment]
Je viens de simplifier la partie développement, c'est mieux ?

**Comment by sikelio** [comment]
C'est déjà mieux
Mais est ce que ce serait pas intéressant d'indiquer quels scripts sont adaptés à Windows et Linux?
Car en ayant testé pnpm run dev sur le cmd de windows, les variables d'environnement ne sont pas autorisées

**Comment by kernoeb** [comment]
Hmm, ok, tu travailles sous Windows !

Je n'ai pas d'appareil avec cet OS chez moi donc je n'ai jamais vraiment testé, il y a juste eu @ShockedPlot7560 qui a vérifié que ça fonctionne.
À priori le plus simple reste de tout faire avec WSL2, d'ailleurs dans ce cas "/opt/" devrait être accepté. Mais je vais le noter, bonne remarque.

Pour les variables d'environnement, une solution serait d'utiliser `cross-env`, pour que ça fonctionne pour tout le monde :)

**Comment by sikelio** [comment]
Yes malheureusement je suis sous windows mais attention je sais utiliser Linux :)
Si jamais, hier soir j'ai réussi à lancer le projet même en étant sous windows :)

**Comment by ShockedPlot7560** [comment]
> Je n'ai pas d'appareil avec cet OS chez moi donc je n'ai jamais vraiment testé, il y a juste eu @ShockedPlot7560 qui a vérifié que ça fonctionne. À priori le plus simple reste de tout faire avec WSL2, d'ailleurs dans ce cas "/opt/" devrait être accepté. Mais je vais le noter, bonne remarque.:)

Je le lance sous WSL donc sous Linux, le plus simple sous Windows.
