### ISSUE TITLE
[IDEA] Make the startup screen in PWA dark

### ISSUE THREAD

**Issue by EDM115** [kernoeb/PlanningSup#116]
on Android, when we use the app as PWA, even if the whole system uses dark mode (and Chrome too), the startup screen is pure white  
  
in video :  
https://github.com/kernoeb/PlanningSup/assets/82015596/8d668d36-ad67-4abd-ad80-931867c63f92

**Comment by kernoeb** [comment]
Effectivement, ça fait mal aux yeux
Je ne suis pas sur de pouvoir varier le splash screen en fonction de la couleur du thème actuel, mais je vais limite le mettre en thème sombre par défaut, ça sera pas très gênant pour les utilisateurs thème clair

**Comment by kernoeb** [comment]
Par contre c'est marrant moi ça apparait comme ça

![Screenshot_20231023-000048_Brave - Beta.png](https://github.com/kernoeb/PlanningSup/assets/24623168/a1a88489-ab4f-4474-b908-76d71e54318a)

**Comment by kernoeb** [comment]
Probablement le commit le plus compliqué de ma vie : https://github.com/kernoeb/PlanningSup/commit/a916e4c125e5afeb066480f4f46de2a6f262fb91

Merci pour le retour !
