### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by Rip01nt** [kernoeb/PlanningSup#120]
Pouvoir se connecter et rajouter des événements personnels

**Comment by kernoeb** [comment]
J'ai déjà eu cette idée il y a quelques temps, mais la question que je me suis posée, pourquoi ne pas utiliser Google Calendar ou autre dans ce genre de situations ? Bien que dans l'idée c'est un peu cool comme fonctionnalité, est-ce que c'est à un planning universitaire de gérer ce genre de cas? Étant donné également que ça ouvre plusieurs questions subsidiaires : où sont stockées les données, comment gérer la synchronisation, que faire en termes de sécurité, comment ajouter des calendriers, etc...
