### ISSUE TITLE
Planning selection menu bug

### ISSUE THREAD

**Issue by ShockedPlot7560** [kernoeb/PlanningSup#51]
Currently there are several focus problems with the selection of schedules in the menus.
* When a new schedule is selected, the background remains blue until another schedule is selected.
*This background should be removed as soon as it is selected*
* When a new schedule is selected and a schedule is deselected, the background of the deselected schedule remains blue.
*The blue background should be removed*
* When you have had the previous bug and you want to reselect a schedule, the background returns to normal but the schedule is not selected
* When you select a schedule by clicking on the checkbox, the checkbox stays in focus and you see a small overlay background behind it

**Comment by kernoeb** [comment]
fixed in branch refactor
