### ISSUE TITLE
[SUGGESTION] Sélection du fuseau horaire 

### ISSUE THREAD

**Issue by finxol** [kernoeb/PlanningSup#58]
Peut-être ajouter un champ dans le volet de paramètres pour la sélection du fuseau horaire à utiliser par le planning ?

## Solution possible
Il y aurait quelques pistes avec la bibliothèque [Moment Timezone](https://momentjs.com/timezone/) ou ce [thread StackOverflow](https://stackoverflow.com/questions/39263321/javascript-get-html-timezone-dropdown).
Une option pourrait être d'afficher l'heure dans le fuseau Europe/Paris par défaut, et en utiliser un autre si un cookie timezone est créé.

**Comment by kernoeb** [comment]
C'est une bonne idée yes, que l'on m'a déjà proposée il y a longtemps
Actuellement c'est l'heure du navigateur qui est utilisée (de manière à ce que ça s'adapte automatiquement), mais on pourrait éventuellement garder la timezone dans un cookie
Comme ça je dirais que l'API ne doit pas changer, mais que juste côté client ça s'affiche différemment, si possible (comme si on changeait la date du navigateur)
Ça me paraîtrait bizarre de décaler l'heure des cours par exemple

**Comment by kernoeb** [comment]
https://github.com/kernoeb/PlanningSup/commit/f8e6f9e34a49d477f282a2965c1d28f23690c60e

C'est une solution qui semble bien fonctionner
Je pense que ça sera désactivé par défaut, et je rajouterai une option dans les paramètres (dans l'UI) pour choisir une TZ/locale)

**Comment by kernoeb** [comment]
Dans la séquentialité, je pensais à quelque chose comme ça :

```js
const TZ = req.cookies?.TZ || process.env.TZ || 'Europe/Paris'
const locale = req.headers['accept-language'] || req.cookies?.locale || 'fr'
```

**Comment by kernoeb** [comment]
Visiblement il y a ce module qui peut aider aussi : https://github.com/smhg/express-locale

**Comment by kernoeb** [comment]
mieux vaut tard que jamais
