### ISSUE TITLE
[Suggestion] Affichage de la barre rouge seulement pour le jour actuel

### ISSUE THREAD

**Issue by Runtehr** [kernoeb/PlanningSup#67]
La barre horizontale rouge qui marque l'heure actuelle est assez pratique. Dans le mode jour, elle s'affiche pour le jour actuel, mais aussi pour les autres, lorsqu'on swipe sur le côté. Ça entraîne parfois des incompréhensions.
Il serait pratique d'avoir un affichage de cet barre uniquement si c'est le jour actuel qui est affiché.

**Comment by kernoeb** [comment]
Corrigé sur ce commit 

https://github.com/kernoeb/PlanningSup/commit/57372f361615b1f7384f9130d6b1bcbdfeb76c1f

Je mets en prod PlanningSup demain, sur quoi je fermerai l'issue

Merci pour le retour !

**Comment by kernoeb** [comment]
En production ! :tada: 

https://github.com/kernoeb/PlanningSup/commit/4ae68389290c044958b32aac0da4bb0f334743ee
