### ISSUE TITLE
[BUG] Encodage caractères

### ISSUE THREAD

**Issue by ShockedPlot7560** [kernoeb/PlanningSup#68]
Si nous avons une apostrophes dans le nom d'un cours, celle ci sera affiché comme un ``?``
Exemple : 
![image](https://user-images.githubusercontent.com/66992287/160233604-278270a4-bfea-4e3d-b3f7-9cde6142a782.png)

**Comment by kernoeb** [comment]
J'avais effectivement déjà remarqué ça
De mémoire le fichier .ics renvoie les données de cette manière de base, mais je ne suis pas sûr 
Si c'est pas le cas, j'essayerai de faire un replace
Je regarde ça aujourd'hui, merci !

**Comment by ShockedPlot7560** [comment]
Super

**Comment by kernoeb** [comment]
Correctif : 

https://github.com/kernoeb/PlanningSup/commit/b512823a8802f7952c4c61fbb45ce7f776f3f25e

Merci !
