### ISSUE TITLE
[Suggestion] Ajout des groupes TP5 et TP6 des 3e année cyberdéfense ENSIBS

### ISSUE THREAD

**Issue by hashp4** [kernoeb/PlanningSup#76]
Le nombre de groupes TP a changé depuis la création du planning. Serait-il possible de le mettre à jour ?

Merci d'avance (;

**Comment by kernoeb** [comment]
Hello!
N'étant plus étudiant depuis plus d'un an, je n'ai pas accès au planning ADE pour faire la mise à jour de mon côté
Par contre, c'est une bonne idée de mettre ça à jour !

Donc pour faire ça : 

- Soit tu peux utiliser le script https://github.com/kernoeb/PlanningSup/blob/main/resources/browser.js et faire une pull request (autant récupérer directement tout ENSIBS)
- Si ce n'est pas possible pour toi, je peux demander à quelqu'un de l'iut de s'en occuper

Je te laisse me dire ça :)

**Comment by kernoeb** [comment]
Merci @ShockedPlot7560 !
