### ISSUE TITLE
[Horaires] Créneau de midi

### ISSUE THREAD

**Issue by EDM115** [kernoeb/PlanningSup#78]
Depuis la rentrée, les cours affichés comme étant de 11h30 à 13h00 sont en réalité de 11h20 à 12h50. Cela s'applique de sûr pour les BUT INFO, mais c'est aussi sûrement pour tout l'IUT  
  
![image](https://user-images.githubusercontent.com/82015596/190600667-8d857be9-0e53-445e-bee1-13f7c2442aae.png)  
  
Serait-il possible de modifier ces valeurs après les avoir prises depuis l'ENT ?

**Comment by kernoeb** [comment]
Hello!

Est-ce que tu pourrais vérifier que cela concerne tout l'IUT ? Sinon je vais essayer de mettre ça en place pour les BUT INFO uniquement

Par contre c'est peut-être un peu dangereux pour des cours autres, genre partiels, etc

**Comment by ShockedPlot7560** [comment]
Cela ne concerne que les BUT INFO, l'année dernière cela était déjà le cas, mais ils n'ont jamais changé sur ADE.  
Donc mettre en place quelque chose juste pour nous peut etre possible, mais risque d'être dangereux dans le futur

**Comment by EDM115** [comment]
> Est-ce que tu pourrais vérifier que cela concerne tout l'IUT ? Sinon je vais essayer de mettre ça en place pour les BUT INFO uniquement

Apparemment c'est que pour les BUT Info

> Par contre c'est peut-être un peu dangereux pour des cours autres, genre partiels, etc

Sans doute, après être là en avance ne peut pas faire de mal 😉
