### ISSUE TITLE
Probleme_semestre

### ISSUE THREAD

**Issue by alex532h** [kernoeb/PlanningSup#88]
Bonsoir,

Le semestre 4 de l'EDT PEI2 (SSI SET - Lorient -> L2 -> L2 PEI) n'est pas pris en compte
Quelqu'un saurait pourquoi?

**Comment by alex532h** [comment]
16 janvier ?
personnellement je n ai rien qui s affiche
pareil pour un camarade de classe

**Comment by alex532h** [comment]
ah si effectivement pour le grp1
Mais je ne comprend pas pourquoi il n affiche pas l entierete de l EDT

**Comment by kernoeb** [comment]
Sur le planning officiel, y a des événements sur ce cours exact ? PlanningSup renvoie ce que l'ics de ce cours là renvoie, donc je peux pas trop vérifier perso

**Comment by alex532h** [comment]
des evenements ?
jvais regarde le planning de l ent ...
ah ok. Tkt jvais essayer de voir

**Comment by kernoeb** [comment]
"événements" dans le sens s'il y a des cours présents (sur un calendrier ics on parle d'events)

**Comment by alex532h** [comment]
bon de ce que je vois ces cours la ne sont meme pas sur l ent mdr

**Comment by alex532h** [comment]
ok mrc pour l explication

**Comment by kernoeb** [comment]
ok bah ça vient pas de PlanningSup alors, je peux close ?

**Comment by alex532h** [comment]
ok
bah jpense que oui
mrc pour tes reponses rapides
